### ISSUE TITLE
create-vanilla-SCDB is broken since

### ISSUE THREAD

**Issue by guillaume-philippon** [quattor/template-library-examples#19]
Hi,

As cluster property is fixed to 14.12.0-rc2 but the quattor release is not yet available, create-vanilla-SCDB.sh didn't work anymore (compilation failed due to missing of quattor/14.12.0-rc2)

Regards,

**Comment by jrha** [comment]
Urgh, it really shouldn't allow you to use RC versions...

**Comment by jouvin** [comment]
@guillaume-philippon is it possible to get more info on this one? 

@jrha yes `create-vanilla-SCDB` can be used to test RC versions. You just have to ask it explicitly. And in this case, everything should be done properly with the example (this part of the release script)....

**Comment by jouvin** [comment]
Ok, pb understood... This is due to the change in tag names and is tracked in issue https://github.com/quattor/release/issues/70. Thus closing this issue.
