### ISSUE TITLE
Definition of Centos7 machine

### ISSUE THREAD

**Issue by almumontiel** [quattor/template-library-examples#38]
Hi, this is more a question than an issue:

I'm trying to install a Centos7 machine.

I have a os/version_db.pan template, where I set the OS_VERSION  = centos750-x86_64. I am using variable OS_FLAVOUR_ENABLED = true.

But I get the error:
[..]
     [panc] evaluation error [/home/almudena/workspace/trunk/cfg/standard/machine-types/core.pan:115.1-115.37]
     [panc] cannot locate template named 'config/core/base'
     [panc] >>> call stack trace
     [panc] >>> [/home/almudena/workspace/trunk/cfg/standard/machine-types/core.pan:115.1-115.37]
     [panc] >>> [/home/almudena/workspace/trunk/cfg/standard/machine-types/perfsonar-ps.pan:5.1-5.33]
  [..]

So it is not seeing the el7.x-86-64 templates.

Do you know what else should I set? Am I missing anything?

**Comment by jouvin** [comment]
@almumontiel probably this is not well documented 😄 `OS_VERSION` should be defined to `el7.x-x86_64`, not to `centos750-x86_64`. It must match the directory name under `os/` where the OS templates are located (and there is one set of template for a major version, thus `7.x`).

What is exactly the version is governed by the YUM repo (snapshot) that you use. How it is defined is not necessarily standard and depends on how your repository are configured. Standard OS templates for EL7 looks for a template called `el7x_x86_64.pan` under `YUM_OS_SNAPSHOT_NS` (which defaults to `YUM_SNAPSHOT_NS` which defaults to `repository/config`!). At LAL for example, our `el7x_x86_64.pan` template contains:

```pan
structure template repository/snapshot/el7x_x86_64;


"name" = "el7x_x86_64";
"owner" = "grid.support@lal.in2p3.fr";
"protocols" = list(
  nlist("name","http",
        "url",YUM_SNAPSHOT_ROOT_URL+"/"+YUM_OS_SNAPSHOT_DATE+"/"+YUM_OS_DISTRIBUTION_NAME+"-x86_64")
);
```
We can then use `YUM_OS_DISTRIBUTION_NAME` to define the repo name we want to use... but in fact we are now using only one which correspond to the rolling repo that receives the new versions when they are released.

I hope it helps!

**Comment by almumontiel** [comment]
Thanks so much for the quick answer.
Just for the record: I think it should be OS_VERSION=el7x-x86_64 without the . (dot), otherwise it does not compile.

**Comment by jouvin** [comment]
You are right! sorry for the typo.
